{
 "title": "Combined Node, IB, GPU & NVLink Metrics Dashboard (w/o GPU Profiling)",
 "description": "Combined Node, IB, GPU & NVLink Metrics Dashboard",
 "tags": [
  "HPC/AI Researcher",
  "HPC/AI Data scientist"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   },
   {
    "name": "instance",
    "label": "Hostname",
    "query": {
     "query": "label_values(node_uname_info{cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": {
     "query": "label_values(node_cpu_seconds_total{instance=\"$instance\"}, cpu)"
    }
   },
   {
    "name": "diskdevices",
    "label": "Disk Devices",
    "query": {
     "query": "label_values(node_disk_reads_completed_total{instance=\"$instance\"}, device)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(dcgm_fi_dev_gpu_util{hostname=\"$instance\"},gpu)"
    }
   },
   {
    "name": "powerlimit",
    "query": {
     "query": "dcgm_fi_dev_power_mgmt_limit{gpu=\"0\", hostname=\"$instance\"}"
    }
   },
   {
    "name": "templimit",
    "query": {
     "query": "dcgm_fi_dev_power_mgmt_limit{gpu=\"0\",instance=\"$instance\"}"
    }
   },
   {
    "name": "physicalhost",
    "query": {
     "query": "label_values(dcgm_fi_dev_power_mgmt_limit{gpu=\"0\", instance=\"$instance\"},physical_host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "table",
   "description": "Node Spec",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"^$instance$\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Load ",
   "type": "gauge",
   "description": "Normalized CPU Load (Load1 / Core Count)",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "scalar(node_load1{instance=\"$instance\", cluster=\"$cluster\"}) * 100 / count(count(node_cpu_seconds_total{instance=\"$instance\", cluster=\"$cluster\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU Utilization",
   "type": "gauge",
   "description": "Average CPU Utilization",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filesystem Used",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance=\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\", cluster=\"$cluster\"} * 100) / node_filesystem_size_bytes{instance=\"$instance\",mountpoint=\"/\",fstype!=\"rootfs\",cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Name",
   "type": "stat",
   "description": "Physical Host Name",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\", cluster=\"$cluster\"} - node_boot_time_seconds{instance=\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time Node has been up",
   "gridPos": { "h": 2, "w": 4, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$instance\", cluster=\"$cluster\"} - node_boot_time_seconds{instance=\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization (avg)",
   "type": "timeseries",
   "description": "CPU Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * (1 - avg by (hostname, cpu) (rate(node_cpu_seconds_total{mode='idle', instance=~\"^$instance$\", cpu=~\"^$cpu$\", cluster=\"$cluster\" }[$__rate_interval]))))",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Clock",
   "type": "timeseries",
   "description": "CPU Clock Speed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "node_cpu_frequency_hertz{instance=~\"^$instance$\", cpu=~\"^$cpu$\", cluster=\"$cluster\"} / 1000000",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "description": "Memory Utilization",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(100 * (1 - node_memory_memavailable_bytes{instance=~\"^$instance$\", cluster=\"$cluster\"} / node_memory_memtotal_bytes{instance=~\"^$instance$\", cluster=\"$cluster\"}))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "timeseries",
   "description": "Available memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_memavailable_bytes{instance=~\"^$instance$\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Major Page Faults",
   "type": "timeseries",
   "description": "Processes waiting on disk-backed memory.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "irate(node_vmstat_pgmajfault{instance=~\"^$instance$\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Filesystem Space",
   "type": "timeseries",
   "description": "Filesystem size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=~\"^$instance$\",device!~\"rootfs\", cluster=\"$cluster\"} - node_filesystem_avail_bytes{instance=~\"^$instance$\",device!~\"rootfs\", cluster=\"$cluster\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Ethernet Throughput (RX/TX)",
   "type": "timeseries",
   "description": "RX/TX rate of VM's Ethernet Interface",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{device='eth0', instance=~\"^$instance$\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - receive"
    },
    {
     "expr": "(rate(node_network_transmit_bytes_total{device='eth0', instance=~\"^$instance$\",cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} - transmit"
    }
   ]
  },
  {
   "title": "Disk I/O Utilization",
   "type": "timeseries",
   "description": "Disk I/O Utilization ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"^$instance$\",device=~\"^$diskdevices$\", cluster=\"$cluster\"} [$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O Operations",
   "type": "timeseries",
   "description": "Disk I/O Operations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"^$instance$\",device=~\"^$diskdevices$\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{device}} - reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=\"^$instance$\",device=~\"^$diskdevices$\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{device}} - writes completed"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "description": "Disk Read/Write Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"^$instance$\",device=~\"^$diskdevices$\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{device}} -read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"^$instance$\",device=~\"^$diskdevices$\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{device}} - write"
    }
   ]
  },
  {
   "title": "NFS I/O Operations",
   "type": "timeseries",
   "description": "NFS I/O Operations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_mountstats_nfs_operations_requests_total{instance=~\"^$instance$\", operation=~\"^READ$\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{export}} - {{operation}}s completed"
    },
    {
     "expr": "irate(node_mountstats_nfs_operations_requests_total{instance=~\"^$instance$\", operation=~\"^WRITE$\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{export}} - {{operation}}s completed"
    }
   ]
  },
  {
   "title": "NFS Throughput",
   "type": "timeseries",
   "description": "NFS Read/Write Throughput",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_mountstats_nfs_total_read_bytes_total{instance=~\"^$instance$\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{export}} - read"
    },
    {
     "expr": "irate(node_mountstats_nfs_total_write_bytes_total{instance=~\"^$instance$\", cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{export}} - write"
    }
   ]
  },
  { "title": "GPU Device Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "type": "table",
   "description": "Node Spec",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "dcgm_fi_dev_gpu_util{hostname=~\"^$instance$\", cluster=\"$cluster\", gpu=\"0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average GPU Utilization",
   "type": "gauge",
   "description": "Average GPU Utilization ",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(dcgm_fi_dev_gpu_util{hostname=~\"^$instance$\", cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Power Usage",
   "type": "gauge",
   "description": "Average Power Usage (Power Draw/Max Power Limit)",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg ((dcgm_fi_dev_power_usage{hostname=~\"^$instance$\",cluster=\"$cluster\"} / dcgm_fi_dev_power_mgmt_limit{hostname=~\"^$instance$\",cluster=\"$cluster\"}) * 100)\r\n\r\n",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Average Temperature Usage ",
   "type": "gauge",
   "description": "Average GPU Temperature (GPU Temp/Max Operating Temp) ",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg ((dcgm_fi_dev_gpu_temp{hostname=~\"^$instance$\",cluster=\"$cluster\"} / dcgm_fi_dev_gpu_max_op_temp{hostname=~\"^$instance$\",cluster=\"$cluster\"}) * 100) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU XID Errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (gpu) (dcgm_fi_dev_xid_errors{hostname=~\"^$instance$\", cluster=\"$cluster\"})",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "description": "GPU utilization (in %)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_gpu_util{hostname=~\"^$instance$\", gpu=~\"^$gpu$\", cluster=\"$cluster\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Copy Utilization",
   "type": "timeseries",
   "description": "Memory utilization (in %)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_mem_copy_util{hostname=\"$instance\", gpu=~\"$gpu\",cluster=\"$cluster\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "SM Clock",
   "type": "timeseries",
   "description": "SM clock frequency (in MHz)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_sm_clock{hostname=~\"^$instance$\", gpu=~\"^$gpu$\",cluster=\"$cluster\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "timeseries",
   "description": "Memory clock frequency (in MHz)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_mem_clock{hostname=~\"^$instance$\", gpu=~\"^$gpu$\",cluster=\"$cluster\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "description": "GPU temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_gpu_temp{hostname=~\"^$instance$\", gpu=~\"^$gpu$\",cluster=\"$cluster\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "timeseries",
   "description": "Memory temperature (in C)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_memory_temp{hostname=~\"^$instance$\", gpu=~\"^$gpu$\",cluster=\"$cluster\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "description": "Power usage (in W)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_power_usage{hostname=~\"^$instance$\", gpu=~\"^$gpu$\",cluster=\"$cluster\"}",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Total Energy Consumption",
   "type": "timeseries",
   "description": "Total energy consumption since boot (in mJ)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "joule" } },
   "targets": [
    {
     "expr": "dcgm_fi_dev_total_energy_consumption{hostname=~\"^$instance$\", gpu=~\"^$gpu$\",cluster=\"$cluster\"} / 10^3",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Last GPU XID Code",
   "type": "table",
   "description": "Last XID Code Present(> 0 indicates XID error)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_XID_ERRORS{hostname=~\"^$instance$\",cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last GPU Throttle Code",
   "type": "table",
   "description": "Last GPU Throttle Code",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_CLOCKS_EVENT_REASONS{hostname=~\"^$instance$\",cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SBE Persistent ECC Errors",
   "type": "timeseries",
   "description": "Total number of single-bit persistent ECC errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_ecc_sbe_agg_total{hostname=~\"^$instance$\", gpu=~\"^$gpu$\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DBE Persistent ECC Errors",
   "type": "timeseries",
   "description": "Total number of double-bit persistent ECC errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_ecc_dbe_agg_total{hostname=~\"^$instance$\", gpu=~\"^$gpu$\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "SBE Volatile ECC Errors",
   "type": "timeseries",
   "description": "Total number of single-bit volatile ECC errors",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_ecc_sbe_vol_total{hostname=~\"^$instance$\", gpu=~\"^$gpu$\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DBE Volatile ECC Errors",
   "type": "timeseries",
   "description": "Total number of double-bit volatile ECC errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_ecc_dbe_vol_total{hostname=~\"^$instance$\", gpu=~\"^$gpu$\",cluster=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Thermal Violation Elapsed Time",
   "type": "timeseries",
   "description": "Thermal Violation Elapsed Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_thermal_violation{hostname=~\"^$instance$\", gpu=~\"^$gpu$\",cluster=\"$cluster\"}[$__rate_interval]) / 1e9",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Power Violation Elapsed Time",
   "type": "timeseries",
   "description": "Power Violation Elapsed Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_power_violation{hostname=~\"^$instance$\", gpu=~\"^$gpu$\",cluster=\"$cluster\"}[$__rate_interval]) / 1e9",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  { "title": "Infiniband Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 130 } },
  {
   "title": "IB Link Status",
   "type": "state-timeline",
   "description": "Indication of IB Link status. Up:1 and Down:0",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_infiniband_physical_state_id{instance=~\"^$instance$\", device!=\"mlx5_an0\",cluster=\"$cluster\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IB Link Flap Status",
   "type": "state-timeline",
   "description": "Indication of IB Link Flap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "targets": [
    {
     "expr": "clamp_max(increase(node_infiniband_link_downed_total{instance=~\"^$instance$\",cluster=\"$cluster\",device!=\"mlx5_an0\"}[$__rate_interval]), 1)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "IB Throughput (RX/TX)",
   "type": "timeseries",
   "description": "The rate of data received/transmitted on the IB port",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_infiniband_port_data_received_bytes_total{instance=~\"^$instance$\",cluster=\"$cluster\", device!=\"mlx5_an0\"}[$__rate_interval])",
     "legendFormat": "{{device}} - receive"
    },
    {
     "expr": "rate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"^$instance$\", cluster=\"$cluster\", device!=\"mlx5_an0\"}[$__rate_interval])",
     "legendFormat": "{{device}} - transmit"
    }
   ]
  },
  {
   "title": "Port Rcv Errors",
   "type": "timeseries",
   "description": "Total number of packets containing an error that were received on the port.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(node_infiniband_port_errors_received_total{instance=~\"^$instance$\", cluster=\"$cluster\",device!=\"mlx5_an0\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Port Rcv Constraint Errors",
   "type": "timeseries",
   "description": "Total number of packets received on the switch physical port that are discarded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(node_infiniband_port_constraint_errors_received_total{instance=~\"^$instance$\",cluster=\"$cluster\", device!=\"mlx5_an0\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Port Xmit Wait",
   "type": "timeseries",
   "description": "Number of ticks during which the port had data to transmit but no data was sent during the entire tick",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 147 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(node_infiniband_port_transmit_wait_total{instance=~\"^$instance$\", cluster=\"$cluster\",device!=\"mlx5_an0\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Port Xmit Constraint Errors",
   "type": "timeseries",
   "description": "Total number of packets not transmitted from the switch physical port.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(node_infiniband_port_constraint_errors_transmitted_total{instance=~\"^$instance$\",cluster=\"$cluster\", device!=\"mlx5_an0\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Port Xmit Discards",
   "type": "timeseries",
   "description": "Total number of outbound packets discarded by the port because the port is down or congested.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(node_infiniband_port_discards_transmitted_total{instance=~\"^$instance$\", cluster=\"$cluster\",device!=\"mlx5_an0\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "NVLink Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 } },
  {
   "title": "Last NVLink Recovery Failed Event",
   "type": "table",
   "description": "Last NVLink Recovery Failed Event",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 164 },
   "targets": [
    {
     "expr": "clamp_max(increase(dcgm_fi_dev_nvlink_count_link_recovery_failed_events{hostname=~\"^$instance$\",cluster=\"$cluster\"}[$__rate_interval]), 1)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Link Integrity Errors",
   "type": "timeseries",
   "description": "Total number of times that the count of local errors exceeded the set threshold",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 164 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_nvlink_count_local_link_integrity_errors{hostname=~\"^$instance$\", cluster=\"$cluster\", gpu=~\"^$gpu$\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "NVLink Throughput (RX/TX)",
   "type": "timeseries",
   "description": "The rate of data received over NVLink, not including protocol headers, in bytes per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(dcgm_fi_prof_nvlink_rx_bytes{hostname=~\"^$instance$\", cluster=\"$cluster\", gpu=~\"^$gpu$\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}} - receive"
    },
    {
     "expr": "rate(dcgm_fi_prof_nvlink_tx_bytes{hostname=~\"^$instance$\",cluster=\"$cluster\", gpu=~\"^$gpu$\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}} - transmit"
    }
   ]
  },
  {
   "title": "Link RX Errors",
   "type": "timeseries",
   "description": "Total number of packets with errors Rx on a link",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_nvlink_count_rx_errors{hostname=~\"^$instance$\",cluster=\"$cluster\", gpu=~\"^$gpu$\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Port TX Discards",
   "type": "timeseries",
   "description": "Total number of TX error packets that were discarded.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dcgm_fi_dev_nvlink_count_tx_discards{hostname=~\"^$instance$\", cluster=\"$cluster\",gpu=~\"^$gpu$\"}[$__rate_interval])",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}